-- CreateEnum
CREATE TYPE "Locale" AS ENUM ('en', 'id');

-- CreateEnum
CREATE TYPE "AssetEngine" AS ENUM ('UNITY', 'UNREAL', 'BLENDER', 'STANDALONE_3D', 'AUDIO', 'IMAGE', 'VIDEO', 'OTHER', 'ENGINE_AGNOSTIC');

-- CreateEnum
CREATE TYPE "AssetStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED', 'DELETED');

-- CreateEnum
CREATE TYPE "AnalysisStatus" AS ENUM ('PENDING', 'ANALYZING', 'READY', 'FAILED');

-- CreateEnum
CREATE TYPE "AssetFileKind" AS ENUM ('UNITYPACKAGE', 'UPLUGIN', 'UPROJECT', 'FBX', 'OBJ', 'GLB', 'GLTF', 'BLEND', 'MAYA', 'TEXTURE_2D', 'SPRITE', 'AUDIO', 'VIDEO', 'ANIMATION', 'SHADER', 'SCRIPT_CS', 'SCRIPT_CPP', 'SCRIPT_PY', 'DOCUMENT', 'ARCHIVE', 'OTHER');

-- CreateEnum
CREATE TYPE "CommentKind" AS ENUM ('COMMENT', 'ISSUE');

-- CreateEnum
CREATE TYPE "IssueStatus" AS ENUM ('OPEN', 'ACKNOWLEDGED', 'RESOLVED');

-- CreateEnum
CREATE TYPE "ReportCategory" AS ENUM ('MALICIOUS_FILE', 'BROKEN_ASSET');

-- CreateEnum
CREATE TYPE "ReportStatus" AS ENUM ('OPEN', 'REVIEWING', 'ACTIONED', 'DISMISSED');

-- CreateEnum
CREATE TYPE "AssetRequestStatus" AS ENUM ('SENT', 'IN_REVIEW', 'PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "DownloadSource" AS ENUM ('WEB', 'UNITY', 'UNREAL');

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('COMMENT_CREATED', 'COMMENT_REPLY', 'ISSUE_CREATED', 'ISSUE_STATUS_CHANGED', 'REQUEST_CREATED', 'REQUEST_STATUS_CHANGED', 'REPORT_CREATED', 'REPORT_RECEIVED_FOR_YOUR_ASSET', 'FEATURED_FEATURED', 'VERSION_PUBLISHED', 'ANALYZER_FAILED', 'ADMIN_PROMOTED', 'ADMIN_DEMOTED');

-- CreateEnum
CREATE TYPE "ReportActionKind" AS ENUM ('NOTHING', 'ARCHIVE_ASSET', 'DELETE_ASSET', 'FORCE_DELETE_ASSET');

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "keycloakSub" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "locale" "Locale" NOT NULL DEFAULT 'en',
    "isAdmin" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "assets" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "licenseId" TEXT NOT NULL,
    "engine" "AssetEngine" NOT NULL,
    "status" "AssetStatus" NOT NULL DEFAULT 'DRAFT',
    "thumbnailKey" TEXT,
    "thumbnailVariants" JSONB,
    "thumbnailAutoGeneratedKey" TEXT,
    "previewMedia" JSONB,
    "requiresEmptyProject" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "publishedAt" TIMESTAMP(3),
    "archivedAt" TIMESTAMP(3),

    CONSTRAINT "assets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_translations" (
    "id" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "locale" "Locale" NOT NULL,
    "shortDescription" TEXT NOT NULL,
    "longDescription" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "asset_translations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_versions" (
    "id" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "semver" TEXT NOT NULL,
    "releaseNotes" JSONB NOT NULL,
    "s3Prefix" TEXT NOT NULL,
    "bytesTotal" BIGINT NOT NULL DEFAULT 0,
    "fileCount" INTEGER NOT NULL DEFAULT 0,
    "manifest" JSONB,
    "analysisStatus" "AnalysisStatus" NOT NULL DEFAULT 'PENDING',
    "isLatest" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "asset_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_files" (
    "id" TEXT NOT NULL,
    "versionId" TEXT NOT NULL,
    "s3Key" TEXT NOT NULL,
    "relativePath" TEXT NOT NULL,
    "bytes" BIGINT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "kind" "AssetFileKind" NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "meta" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "asset_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "engine_compatibility" (
    "id" TEXT NOT NULL,
    "versionId" TEXT NOT NULL,
    "engineVersion" TEXT NOT NULL,
    "renderPipelines" TEXT[],
    "targets" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "engine_compatibility_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_dependencies" (
    "id" TEXT NOT NULL,
    "versionId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "version" TEXT,
    "source" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "asset_dependencies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "categories" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" JSONB NOT NULL,
    "iconKey" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tags" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_tags" (
    "assetId" TEXT NOT NULL,
    "tagId" TEXT NOT NULL,

    CONSTRAINT "asset_tags_pkey" PRIMARY KEY ("assetId","tagId")
);

-- CreateTable
CREATE TABLE "licenses" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" JSONB NOT NULL,
    "fullText" JSONB NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "licenses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "library_items" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "hidden" BOOLEAN NOT NULL DEFAULT false,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "library_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "downloads" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "versionId" TEXT NOT NULL,
    "fileId" TEXT,
    "ipHash" TEXT NOT NULL,
    "country" TEXT,
    "userAgent" TEXT NOT NULL,
    "source" "DownloadSource" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "downloads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "comments" (
    "id" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "authorId" TEXT NOT NULL,
    "parentId" TEXT,
    "kind" "CommentKind" NOT NULL DEFAULT 'COMMENT',
    "body" JSONB NOT NULL,
    "status" "IssueStatus",
    "depth" INTEGER NOT NULL DEFAULT 0,
    "editedAt" TIMESTAMP(3),
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reports" (
    "id" TEXT NOT NULL,
    "reporterId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "category" "ReportCategory" NOT NULL,
    "notes" TEXT NOT NULL,
    "status" "ReportStatus" NOT NULL DEFAULT 'OPEN',
    "adminNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),

    CONSTRAINT "reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_requests" (
    "id" TEXT NOT NULL,
    "requesterId" TEXT NOT NULL,
    "assetLink" TEXT NOT NULL,
    "assetType" TEXT NOT NULL,
    "intendedUse" TEXT NOT NULL,
    "price" DECIMAL(12,2),
    "notes" TEXT,
    "status" "AssetRequestStatus" NOT NULL DEFAULT 'SENT',
    "adminComment" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "asset_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "featured_slots" (
    "id" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL,
    "customBannerKey" TEXT,
    "customTitle" TEXT,
    "customShortDescription" JSONB,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "featured_slots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "payload" JSONB NOT NULL,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "plugin_device_tokens" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "deviceLabel" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "lastUsedAt" TIMESTAMP(3),
    "revokedAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "plugin_device_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "settings" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedById" TEXT,

    CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "editor_media_uploads" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "uploaderId" TEXT NOT NULL,
    "mimeType" TEXT,
    "bytes" BIGINT NOT NULL DEFAULT 0,
    "referenced" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "editor_media_uploads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset_stats" (
    "assetId" TEXT NOT NULL,
    "totalDownloads" INTEGER NOT NULL DEFAULT 0,
    "totalSaves" INTEGER NOT NULL DEFAULT 0,
    "last7dDownloads" INTEGER NOT NULL DEFAULT 0,
    "last30dDownloads" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "asset_stats_pkey" PRIMARY KEY ("assetId")
);

-- CreateTable
CREATE TABLE "download_daily" (
    "id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "assetId" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "uniqueUsers" INTEGER NOT NULL DEFAULT 0,
    "byCountry" JSONB NOT NULL DEFAULT '{}',
    "bySource" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "download_daily_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tag_usage" (
    "tagId" TEXT NOT NULL,
    "usageCount" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tag_usage_pkey" PRIMARY KEY ("tagId")
);

-- CreateTable
CREATE TABLE "storage_daily" (
    "id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "bucket" TEXT NOT NULL,
    "prefix" TEXT NOT NULL,
    "bytes" BIGINT NOT NULL DEFAULT 0,
    "objectCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "storage_daily_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "storage_user_daily" (
    "id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "userId" TEXT NOT NULL,
    "bytes" BIGINT NOT NULL DEFAULT 0,
    "assetCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "storage_user_daily_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "storage_asset_daily" (
    "id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "assetId" TEXT NOT NULL,
    "bytes" BIGINT NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "storage_asset_daily_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_keycloakSub_key" ON "users"("keycloakSub");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "users_email_idx" ON "users"("email");

-- CreateIndex
CREATE INDEX "users_keycloakSub_idx" ON "users"("keycloakSub");

-- CreateIndex
CREATE UNIQUE INDEX "assets_slug_key" ON "assets"("slug");

-- CreateIndex
CREATE INDEX "assets_status_idx" ON "assets"("status");

-- CreateIndex
CREATE INDEX "assets_engine_idx" ON "assets"("engine");

-- CreateIndex
CREATE INDEX "assets_categoryId_idx" ON "assets"("categoryId");

-- CreateIndex
CREATE INDEX "assets_licenseId_idx" ON "assets"("licenseId");

-- CreateIndex
CREATE INDEX "assets_ownerId_idx" ON "assets"("ownerId");

-- CreateIndex
CREATE INDEX "assets_publishedAt_idx" ON "assets"("publishedAt" DESC);

-- CreateIndex
CREATE INDEX "assets_archivedAt_idx" ON "assets"("archivedAt");

-- CreateIndex
CREATE INDEX "asset_translations_assetId_idx" ON "asset_translations"("assetId");

-- CreateIndex
CREATE UNIQUE INDEX "asset_translations_assetId_locale_key" ON "asset_translations"("assetId", "locale");

-- CreateIndex
CREATE INDEX "asset_versions_assetId_idx" ON "asset_versions"("assetId");

-- CreateIndex
CREATE INDEX "asset_versions_analysisStatus_idx" ON "asset_versions"("analysisStatus");

-- CreateIndex
CREATE INDEX "asset_versions_isLatest_idx" ON "asset_versions"("isLatest");

-- CreateIndex
CREATE UNIQUE INDEX "asset_versions_assetId_semver_key" ON "asset_versions"("assetId", "semver");

-- CreateIndex
CREATE INDEX "asset_files_versionId_idx" ON "asset_files"("versionId");

-- CreateIndex
CREATE INDEX "asset_files_kind_idx" ON "asset_files"("kind");

-- CreateIndex
CREATE INDEX "engine_compatibility_versionId_idx" ON "engine_compatibility"("versionId");

-- CreateIndex
CREATE INDEX "engine_compatibility_engineVersion_idx" ON "engine_compatibility"("engineVersion");

-- CreateIndex
CREATE INDEX "asset_dependencies_versionId_idx" ON "asset_dependencies"("versionId");

-- CreateIndex
CREATE INDEX "asset_dependencies_name_idx" ON "asset_dependencies"("name");

-- CreateIndex
CREATE UNIQUE INDEX "categories_slug_key" ON "categories"("slug");

-- CreateIndex
CREATE INDEX "categories_sortOrder_idx" ON "categories"("sortOrder");

-- CreateIndex
CREATE INDEX "categories_isActive_idx" ON "categories"("isActive");

-- CreateIndex
CREATE UNIQUE INDEX "tags_slug_key" ON "tags"("slug");

-- CreateIndex
CREATE INDEX "asset_tags_tagId_idx" ON "asset_tags"("tagId");

-- CreateIndex
CREATE UNIQUE INDEX "licenses_slug_key" ON "licenses"("slug");

-- CreateIndex
CREATE INDEX "licenses_sortOrder_idx" ON "licenses"("sortOrder");

-- CreateIndex
CREATE INDEX "licenses_isActive_idx" ON "licenses"("isActive");

-- CreateIndex
CREATE INDEX "library_items_userId_idx" ON "library_items"("userId");

-- CreateIndex
CREATE INDEX "library_items_assetId_idx" ON "library_items"("assetId");

-- CreateIndex
CREATE UNIQUE INDEX "library_items_userId_assetId_key" ON "library_items"("userId", "assetId");

-- CreateIndex
CREATE INDEX "downloads_assetId_createdAt_idx" ON "downloads"("assetId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "downloads_userId_createdAt_idx" ON "downloads"("userId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "downloads_versionId_idx" ON "downloads"("versionId");

-- CreateIndex
CREATE INDEX "downloads_source_idx" ON "downloads"("source");

-- CreateIndex
CREATE INDEX "downloads_createdAt_idx" ON "downloads"("createdAt" DESC);

-- CreateIndex
CREATE INDEX "comments_assetId_createdAt_idx" ON "comments"("assetId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "comments_parentId_idx" ON "comments"("parentId");

-- CreateIndex
CREATE INDEX "comments_authorId_idx" ON "comments"("authorId");

-- CreateIndex
CREATE INDEX "comments_kind_idx" ON "comments"("kind");

-- CreateIndex
CREATE INDEX "comments_parentId_deletedAt_idx" ON "comments"("parentId", "deletedAt");

-- CreateIndex
CREATE INDEX "reports_status_idx" ON "reports"("status");

-- CreateIndex
CREATE INDEX "reports_assetId_idx" ON "reports"("assetId");

-- CreateIndex
CREATE INDEX "reports_reporterId_idx" ON "reports"("reporterId");

-- CreateIndex
CREATE INDEX "asset_requests_status_idx" ON "asset_requests"("status");

-- CreateIndex
CREATE INDEX "asset_requests_requesterId_idx" ON "asset_requests"("requesterId");

-- CreateIndex
CREATE UNIQUE INDEX "featured_slots_assetId_key" ON "featured_slots"("assetId");

-- CreateIndex
CREATE UNIQUE INDEX "featured_slots_sortOrder_key" ON "featured_slots"("sortOrder");

-- CreateIndex
CREATE INDEX "featured_slots_isActive_sortOrder_idx" ON "featured_slots"("isActive", "sortOrder");

-- CreateIndex
CREATE INDEX "notifications_userId_createdAt_idx" ON "notifications"("userId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "notifications_userId_readAt_idx" ON "notifications"("userId", "readAt");

-- CreateIndex
CREATE INDEX "notifications_userId_readAt_createdAt_idx" ON "notifications"("userId", "readAt", "createdAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "plugin_device_tokens_tokenHash_key" ON "plugin_device_tokens"("tokenHash");

-- CreateIndex
CREATE INDEX "plugin_device_tokens_userId_idx" ON "plugin_device_tokens"("userId");

-- CreateIndex
CREATE INDEX "plugin_device_tokens_revokedAt_idx" ON "plugin_device_tokens"("revokedAt");

-- CreateIndex
CREATE INDEX "plugin_device_tokens_expiresAt_idx" ON "plugin_device_tokens"("expiresAt");

-- CreateIndex
CREATE INDEX "audit_logs_actorId_idx" ON "audit_logs"("actorId");

-- CreateIndex
CREATE INDEX "audit_logs_action_idx" ON "audit_logs"("action");

-- CreateIndex
CREATE INDEX "audit_logs_subjectType_subjectId_idx" ON "audit_logs"("subjectType", "subjectId");

-- CreateIndex
CREATE INDEX "audit_logs_createdAt_idx" ON "audit_logs"("createdAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "settings_key_key" ON "settings"("key");

-- CreateIndex
CREATE UNIQUE INDEX "editor_media_uploads_key_key" ON "editor_media_uploads"("key");

-- CreateIndex
CREATE INDEX "editor_media_uploads_uploaderId_idx" ON "editor_media_uploads"("uploaderId");

-- CreateIndex
CREATE INDEX "editor_media_uploads_referenced_createdAt_idx" ON "editor_media_uploads"("referenced", "createdAt");

-- CreateIndex
CREATE INDEX "download_daily_date_idx" ON "download_daily"("date");

-- CreateIndex
CREATE UNIQUE INDEX "download_daily_assetId_date_key" ON "download_daily"("assetId", "date");

-- CreateIndex
CREATE INDEX "tag_usage_usageCount_idx" ON "tag_usage"("usageCount" DESC);

-- CreateIndex
CREATE INDEX "storage_daily_date_idx" ON "storage_daily"("date");

-- CreateIndex
CREATE UNIQUE INDEX "storage_daily_date_bucket_prefix_key" ON "storage_daily"("date", "bucket", "prefix");

-- CreateIndex
CREATE INDEX "storage_user_daily_date_idx" ON "storage_user_daily"("date");

-- CreateIndex
CREATE INDEX "storage_user_daily_userId_idx" ON "storage_user_daily"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "storage_user_daily_date_userId_key" ON "storage_user_daily"("date", "userId");

-- CreateIndex
CREATE INDEX "storage_asset_daily_date_idx" ON "storage_asset_daily"("date");

-- CreateIndex
CREATE INDEX "storage_asset_daily_assetId_idx" ON "storage_asset_daily"("assetId");

-- CreateIndex
CREATE UNIQUE INDEX "storage_asset_daily_date_assetId_key" ON "storage_asset_daily"("date", "assetId");

-- AddForeignKey
ALTER TABLE "assets" ADD CONSTRAINT "assets_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "assets" ADD CONSTRAINT "assets_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "assets" ADD CONSTRAINT "assets_licenseId_fkey" FOREIGN KEY ("licenseId") REFERENCES "licenses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_translations" ADD CONSTRAINT "asset_translations_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_versions" ADD CONSTRAINT "asset_versions_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_files" ADD CONSTRAINT "asset_files_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "asset_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "engine_compatibility" ADD CONSTRAINT "engine_compatibility_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "asset_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_dependencies" ADD CONSTRAINT "asset_dependencies_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "asset_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_tags" ADD CONSTRAINT "asset_tags_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_tags" ADD CONSTRAINT "asset_tags_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_items" ADD CONSTRAINT "library_items_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_items" ADD CONSTRAINT "library_items_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "downloads" ADD CONSTRAINT "downloads_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "downloads" ADD CONSTRAINT "downloads_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "downloads" ADD CONSTRAINT "downloads_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "asset_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "downloads" ADD CONSTRAINT "downloads_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "asset_files"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reports" ADD CONSTRAINT "reports_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reports" ADD CONSTRAINT "reports_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_requests" ADD CONSTRAINT "asset_requests_requesterId_fkey" FOREIGN KEY ("requesterId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "featured_slots" ADD CONSTRAINT "featured_slots_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "plugin_device_tokens" ADD CONSTRAINT "plugin_device_tokens_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "settings" ADD CONSTRAINT "settings_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "editor_media_uploads" ADD CONSTRAINT "editor_media_uploads_uploaderId_fkey" FOREIGN KEY ("uploaderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "asset_stats" ADD CONSTRAINT "asset_stats_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "download_daily" ADD CONSTRAINT "download_daily_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tag_usage" ADD CONSTRAINT "tag_usage_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE;

