/**
 * Hand-typed slice of the API surface used by the frontend.
 * Full type definitions are generated by `pnpm openapi:gen` into
 * `./schema.ts`. These hand-types stay in sync via PR review.
 */

export type LocaleCode = 'en' | 'id';

export type Engine =
  | 'UNITY'
  | 'UNREAL'
  | 'BLENDER'
  | 'STANDALONE_3D'
  | 'AUDIO'
  | 'IMAGE'
  | 'VIDEO'
  | 'OTHER'
  | 'ENGINE_AGNOSTIC';

export type AssetStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' | 'DELETED';

export type AnalysisStatus = 'PENDING' | 'ANALYZING' | 'READY' | 'FAILED';


export type FileKind =
  | 'UNITYPACKAGE'
  | 'UPLUGIN'
  | 'UNITY_PROJECT'
  | 'UNREAL_PROJECT'
  | 'GLB'
  | 'FBX'
  | 'OBJ'
  | 'TEXTURE_2D'
  | 'SPRITE'
  | 'NORMAL_MAP'
  | 'MATERIAL'
  | 'SHADER'
  | 'AUDIO'
  | 'VIDEO'
  | 'SCRIPT'
  | 'PREFAB'
  | 'SCENE'
  | 'ARCHIVE'
  | 'OTHER';

export type SortOrder =
  | 'newest'
  | 'mostDownloaded'
  | 'recentlyUpdated'
  | 'alphabetical'
  | 'mostSaved';

export type LibrarySort = 'savedAt' | 'alphabetical' | 'recentlyUpdated';

export type HiddenFilter = 'true' | 'false' | 'all';

export type DownloadSource = 'WEB' | 'UNITY' | 'UNREAL';

export type RenderPipeline =
  // Unity
  | 'URP'
  | 'HDRP'
  | 'SRP'
  | 'BUILT_IN'
  // Unreal
  | 'LUMEN'
  | 'NANITE'
  | 'PATH_TRACING'
  // Blender
  | 'EEVEE'
  | 'CYCLES'
  | 'NA';

export type TargetPlatform =
  | 'WINDOWS'
  | 'MAC'
  | 'LINUX'
  | 'IOS'
  | 'ANDROID'
  | 'CONSOLE'
  | 'WEB'
  | 'VR';

export interface ServerAvatar {
  initials: string;
  bgColor: 'brand-blue' | 'brand-yellow' | 'brand-red' | 'brand-green';
  fgColor: string;
}

export interface MeResponse {
  id: string;
  email: string;
  displayName: string;
  locale: LocaleCode;
  isAdmin: boolean;
  role: 'admin' | 'contributor' | 'user';
  avatar: ServerAvatar;
  hasPublishedAssets: boolean;
  unreadNotifications: number;
  createdAt: string;
}

export interface PageInfo {
  nextCursor: string | null;
  hasMore: boolean;
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  iconKey: string | null;
  sortOrder: number;
  assetCount: number;
}

export interface Tag {
  id: string;
  slug: string;
  displayName: string;
  usageCount: number;
}

export interface LicenseSummary {
  id: string;
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
}

export interface AssetSummary {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  engine: Engine;
  status: AssetStatus;
  thumbnailUrl: string | null;
  ownerDisplayName: string;
  categoryName: string;
  totalDownloads: number;
  totalSaves: number;
  updatedAt: string;
  publishedAt: string | null;
}

export interface AssetListPage {
  items: AssetSummary[];
  pageInfo: PageInfo;
}

export interface AssetFile {
  id: string;
  relativePath: string;
  kind: FileKind | string;
  bytes: string; // bigint as string
  meta?: Record<string, unknown> | null;
}

export interface CompatibilityRow {
  engineVersion: string;
  renderPipelines: RenderPipeline[];
  targets: TargetPlatform[];
}

export interface AssetDependency {
  name: string;
  version: string | null;
  source: string;
}

export interface VersionSummary {
  id: string;
  semver: string;
  isLatest: boolean;
  analysisStatus: AnalysisStatus;
  publishedAt: string | null;
  bytesTotal: string;
  fileCount: number;
  createdAt: string;
}

export interface AssetVersionPayload {
  id: string;
  semver: string;
  releaseNotes: TipTapDoc | null;
  publishedAt: string | null;
  isLatest: boolean;
  analysisStatus: AnalysisStatus;
  bytesTotal: string;
  fileCount: number;
  files: AssetFile[];
  compatibility: CompatibilityRow[];
  dependencies: AssetDependency[];
  requiresEmptyProject: boolean;
}

export type PreviewMediaVisibility = 'visible' | 'blur' | 'hidden';

export interface PreviewMediaItem {
  id: string;
  kind: 'image' | 'video' | 'audio' | '3d';
  key: string;
  /** Compressed display variant key (images only). */
  displayKey?: string;
  label: string;
  /** Fast display URL (compressed if available). */
  viewUrl: string;
  /** Full-resolution URL for click-to-enlarge. */
  originalUrl?: string;
  mime?: string;
  visibility?: PreviewMediaVisibility;
  warning?: string;
}

export interface AssetDetail {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  longDescription: TipTapDoc | null;
  availableLocales: LocaleCode[];
  engine: Engine;
  category: { id: string; slug: string; name: string };
  license: { id: string; slug: string; name: string };
  tags: { id: string; slug: string; displayName: string }[];
  thumbnail: { key: string | null; url: string | null };
  thumbnailAutoGenerated: { key: string; url: string } | null;
  previewMedia: PreviewMediaItem[];
  owner: { id: string; displayName: string; avatar: ServerAvatar };
  versions: AssetVersionPayload[];
  totalDownloads: number;
  totalSaves: number;
  status: AssetStatus;
  publishedAt: string | null;
  updatedAt: string;
  createdAt: string;
  isSaved: boolean;
  canEdit: boolean;
  canDelete: boolean;
  canArchive: boolean;
}

export interface FeaturedSlot {
  id: string;
  assetId: string;
  assetSlug: string;
  title: string;
  shortDescription: string;
  bannerUrl: string | null;
  sortOrder: number;
}

export interface DiscoverRow {
  categoryId: string;
  categorySlug: string;
  name: string;
  assets: AssetSummary[];
}

export interface DiscoverResponse {
  featured: FeaturedSlot[];
  rows: DiscoverRow[];
}

export interface LibraryItem {
  addedAt: string;
  hidden: boolean;
  asset: AssetSummary;
}

export interface LibraryPage {
  items: LibraryItem[];
  pageInfo: PageInfo;
}

export interface DownloadOptionsFile {
  id: string;
  relativePath: string;
  kind: string;
  bytes: string;
  getUrl: string | null;
  expiresAt: string | null;
}

export interface DownloadOptions {
  asset: { id: string; title: string };
  version: { id: string; semver: string; releaseNotes: TipTapDoc | null };
  files: DownloadOptionsFile[];
  olderVersions: { id: string; semver: string; publishedAt: string | null }[];
}

export interface SearchAssetHit {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  thumbnailUrl: string | null;
  engine: Engine;
  categoryName: string;
  ownerName: string;
  totalDownloads: number;
}

export interface SearchAssetsResponse {
  hits: SearchAssetHit[];
  processingTimeMs: number;
  estimatedTotalHits: number;
}

export type NotificationType =
  | 'COMMENT_CREATED'
  | 'COMMENT_REPLY'
  | 'ISSUE_CREATED'
  | 'ISSUE_STATUS_CHANGED'
  | 'REQUEST_CREATED'
  | 'REQUEST_STATUS_CHANGED'
  | 'REPORT_CREATED'
  | 'REPORT_RECEIVED_FOR_YOUR_ASSET'
  | 'FEATURED_FEATURED'
  | 'VERSION_PUBLISHED'
  | 'ANALYZER_FAILED'
  | 'ADMIN_PROMOTED'
  | 'ADMIN_DEMOTED';

export interface NotificationItem {
  id: string;
  type: NotificationType | string;
  payload: Record<string, unknown>;
  readAt: string | null;
  createdAt: string;
}

export interface NotificationPage {
  items: NotificationItem[];
  pageInfo: PageInfo;
}

export type AssetRequestStatus =
  | 'SENT'
  | 'IN_REVIEW'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED';

export interface AssetRequest {
  id: string;
  assetLink: string;
  assetType: string;
  intendedUse: string;
  price: number | null;
  notes: string | null;
  status: AssetRequestStatus;
  adminComment: string | null;
  createdAt: string;
  updatedAt: string;
  requester: { id: string; displayName: string };
}

export interface AssetRequestListPage {
  items: AssetRequest[];
  pageInfo: PageInfo;
}

export interface CreateAssetRequestInput {
  assetLink: string;
  assetType: string;
  intendedUse: string;
  price?: number;
  notes?: string;
}

export type CommentKind = 'COMMENT' | 'ISSUE';
export type IssueStatus = 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED';

export interface CommentAuthor {
  id: string;
  displayName: string;
  avatar: ServerAvatar;
}

export interface CommentNode {
  id: string;
  kind: CommentKind;
  parentId: string | null;
  depth: number;
  body: TipTapDoc;
  status: IssueStatus | null;
  editedAt: string | null;
  createdAt: string;
  author: CommentAuthor;
  replies: CommentNode[];
}

export interface CommentListResponse {
  items: CommentNode[];
  pageInfo: PageInfo;
}

export interface CreateCommentInput {
  kind: CommentKind;
  parentId?: string | null;
  body: TipTapDoc;
}

export type AnalysisJobStatus = AnalysisStatus;

export interface AssetAnalyticsSummary {
  totals: { downloads: number; saves: number; downloads7d: number; downloads30d: number };
  topAssets: { id: string; title: string; downloads: number; saves: number }[];
  daily90d: { date: string; count: number }[];
}

export interface AssetAnalyticsDetail {
  asset: { id: string; title: string };
  daily: { date: string; count: number }[];
  /** keys: ISO 3166 country codes (and possibly "unknown"). */
  byCountry: Record<string, number>;
  /** keys: 'WEB' | 'UNITY' | 'UNREAL'. */
  bySource: Record<string, number>;
  byVersion: { versionId: string; semver: string; downloads: number }[];
  byFile: { fileId: string; relativePath: string; downloads: number }[];
}

/* =========================================================================
 * TipTap document model — read-only subset.
 * ========================================================================= */
export interface TipTapDoc {
  type: 'doc';
  content?: TipTapNode[];
}

export interface TipTapMark {
  type: string;
  attrs?: Record<string, unknown>;
}

export interface TipTapNode {
  type: string;
  attrs?: Record<string, unknown>;
  content?: TipTapNode[];
  text?: string;
  marks?: TipTapMark[];
}
