/**
 * Hand-typed slice of the API surface used by the frontend.
 * Full type definitions are generated by `pnpm openapi:gen` into
 * `./schema.ts`. These hand-types stay in sync via PR review.
 */

export type LocaleCode = 'en' | 'id';

export type Engine =
  | 'UNITY'
  | 'UNREAL'
  | 'BLENDER'
  | 'STANDALONE_3D'
  | 'AUDIO'
  | 'IMAGE'
  | 'VIDEO'
  | 'OTHER'
  | 'ENGINE_AGNOSTIC';

export type AssetStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' | 'DELETED';

export type AnalysisStatus = 'PENDING' | 'ANALYZING' | 'READY' | 'FAILED';


export type FileKind =
  | 'UNITYPACKAGE'
  | 'UPLUGIN'
  | 'UNITY_PROJECT'
  | 'UNREAL_PROJECT'
  | 'GLB'
  | 'FBX'
  | 'OBJ'
  | 'TEXTURE_2D'
  | 'SPRITE'
  | 'NORMAL_MAP'
  | 'MATERIAL'
  | 'SHADER'
  | 'AUDIO'
  | 'VIDEO'
  | 'SCRIPT'
  | 'PREFAB'
  | 'SCENE'
  | 'ARCHIVE'
  | 'OTHER';

export type SortOrder =
  | 'newest'
  | 'mostDownloaded'
  | 'recentlyUpdated'
  | 'alphabetical'
  | 'mostSaved';

export type LibrarySort = 'savedAt' | 'alphabetical' | 'recentlyUpdated';

export type HiddenFilter = 'true' | 'false' | 'all';

export type DownloadSource = 'WEB' | 'UNITY' | 'UNREAL';

export type RenderPipeline =
  // Unity
  | 'URP'
  | 'HDRP'
  | 'SRP'
  | 'BUILT_IN'
  // Unreal
  | 'LUMEN'
  | 'NANITE'
  | 'PATH_TRACING'
  // Blender
  | 'EEVEE'
  | 'CYCLES'
  | 'NA';

export type TargetPlatform =
  | 'WINDOWS'
  | 'MAC'
  | 'LINUX'
  | 'IOS'
  | 'ANDROID'
  | 'CONSOLE'
  | 'WEB'
  | 'VR';

export interface ServerAvatar {
  initials: string;
  bgColor: 'brand-blue' | 'brand-yellow' | 'brand-red' | 'brand-green';
  fgColor: string;
}

export interface MeResponse {
  id: string;
  email: string;
  displayName: string;
  locale: LocaleCode;
  isAdmin: boolean;
  role: 'admin' | 'contributor' | 'user';
  avatar: ServerAvatar;
  hasPublishedAssets: boolean;
  unreadNotifications: number;
  createdAt: string;
}

export interface PageInfo {
  nextCursor: string | null;
  hasMore: boolean;
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  iconKey: string | null;
  sortOrder: number;
  assetCount: number;
}

export interface Tag {
  id: string;
  slug: string;
  displayName: string;
  usageCount: number;
}

export interface LicenseSummary {
  id: string;
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
}

export interface AssetSummary {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  engine: Engine;
  status: AssetStatus;
  thumbnailUrl: string | null;
  ownerDisplayName: string;
  categoryName: string;
  totalDownloads: number;
  totalSaves: number;
  updatedAt: string;
  publishedAt: string | null;
}

export interface AssetListPage {
  items: AssetSummary[];
  pageInfo: PageInfo;
}

export interface AssetFile {
  id: string;
  relativePath: string;
  kind: FileKind | string;
  bytes: string; // bigint as string
  meta?: Record<string, unknown> | null;
}

export interface CompatibilityRow {
  engineVersion: string;
  renderPipelines: RenderPipeline[];
  targets: TargetPlatform[];
}

export interface AssetDependency {
  name: string;
  version: string | null;
  source: string;
}

export interface VersionSummary {
  id: string;
  semver: string;
  isLatest: boolean;
  analysisStatus: AnalysisStatus;
  publishedAt: string | null;
  bytesTotal: string;
  fileCount: number;
  createdAt: string;
}

export interface AssetVersionPayload {
  id: string;
  semver: string;
  releaseNotes: TipTapDoc | null;
  publishedAt: string | null;
  isLatest: boolean;
  analysisStatus: AnalysisStatus;
  bytesTotal: string;
  fileCount: number;
  files: AssetFile[];
  compatibility: CompatibilityRow[];
  dependencies: AssetDependency[];
  requiresEmptyProject: boolean;
}

export type PreviewMediaVisibility = 'visible' | 'blur' | 'hidden';

export interface PreviewMediaItem {
  id: string;
  kind: 'image' | 'video' | 'audio' | '3d';
  key: string;
  /** Compressed display variant key (images only). */
  displayKey?: string;
  label: string;
  /** Fast display URL (compressed if available). */
  viewUrl: string;
  /** Full-resolution URL for click-to-enlarge. */
  originalUrl?: string;
  mime?: string;
  visibility?: PreviewMediaVisibility;
  warning?: string;
}

export interface AssetDetail {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  longDescription: TipTapDoc | null;
  availableLocales: LocaleCode[];
  engine: Engine;
  category: { id: string; slug: string; name: string };
  license: { id: string; slug: string; name: string };
  tags: { id: string; slug: string; displayName: string }[];
  thumbnail: { key: string | null; url: string | null };
  thumbnailAutoGenerated: { key: string; url: string } | null;
  previewMedia: PreviewMediaItem[];
  owner: { id: string; displayName: string; avatar: ServerAvatar };
  versions: AssetVersionPayload[];
  totalDownloads: number;
  totalSaves: number;
  status: AssetStatus;
  publishedAt: string | null;
  updatedAt: string;
  createdAt: string;
  isSaved: boolean;
