'use client';

import { useMemo, useState } from 'react';
import NextLink from 'next/link';
import { Share2, Flag, Download } from 'lucide-react';
import { useLocale, useTranslations } from 'next-intl';
import { Container } from '@/components/layout/container';
import { Breadcrumbs } from '@/components/ui/breadcrumbs';
import { Button } from '@/components/ui/button';
import { Alert } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Avatar } from '@/components/ui/avatar';
import { avatarFromServer } from '@/lib/avatar';
import { AssetMeta } from './asset-meta';
import { VersionBadge } from './version-badge';
import { SaveButton } from './save-button';
import { MediaGallery, classifyFiles, type MediaItem } from './media-gallery';
import { AssetTabs } from './asset-tabs';
import { RecommendedAssets } from './recommended-assets';
import { DownloadPopup } from './download-popup';
import { ShareModal } from './share-modal';
import { ReportModal } from './report-modal';
import { CommentsSection } from '@/components/comments/comments-section';
import { formatDate, formatNumber } from '@/lib/format';
import { publicEnv } from '@/lib/env.public';
import { logEvent } from '@/lib/logger.events';
import { usePageView } from '@/lib/hooks/use-page-view';
import type { AssetDetail, AssetVersionPayload, LocaleCode, MeResponse } from '@/lib/api/types';

interface AssetDetailShellProps {
  asset: AssetDetail;
  currentUserId: string;
  isAdmin: boolean;
  me?: MeResponse;
}

export function AssetDetailShell({
  asset,
  currentUserId,
  isAdmin,
  me,
}: AssetDetailShellProps) {
  const meForComments = me;
  const t = useTranslations('asset');
  const tCommon = useTranslations('common');
  const locale = useLocale() as LocaleCode;
  const [downloadOpen, setDownloadOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [reportOpen, setReportOpen] = useState(false);
  const [requestedVersionId, setRequestedVersionId] = useState<string | null>(null);

  usePageView('asset.detail', { assetId: asset.id });

  const latestVersion = useMemo<AssetVersionPayload | null>(
    () => asset.versions.find((v) => v.isLatest) ?? asset.versions[0] ?? null,
    [asset.versions],
  );

  const isOwner = asset.owner.id === currentUserId;
  const showReport = !isOwner && !isAdmin;

  const mediaItems = useMemo<MediaItem[]>(() => {
    const items: MediaItem[] = [];
    const thumbUrl = asset.thumbnail.url ?? asset.thumbnailAutoGenerated?.url ?? null;
    if (thumbUrl) {
      items.push({
        id: `thumb-${asset.id}`,
        kind: 'image',
        url: thumbUrl,
        label: asset.title,
      });
    }
    // Owner-curated gallery from the publish wizard (image / video / audio / 3d).
    for (const m of asset.previewMedia ?? []) {
      if (m.visibility === 'hidden') continue; // never surfaced
      items.push({
        id: m.id,
        kind: m.kind,
        url: m.viewUrl,
        fullUrl: m.originalUrl ?? m.viewUrl,
        label: m.label,
        blur: m.visibility === 'blur',
        warning: m.warning,
      });
    }
    // Anything derivable from the asset's actual package files (e.g. a GLB
    // converted from an FBX, embedded textures with viewUrl metadata).
    if (latestVersion) items.push(...classifyFiles(latestVersion.files));
    return items;
  }, [asset, latestVersion]);

  const shareUrl =
    typeof window !== 'undefined'
      ? window.location.href
      : `${publicEnv.NEXT_PUBLIC_APP_URL.replace(/\/$/, '')}/assets/${asset.slug}`;

  const requestedLocaleAvailable = asset.availableLocales.includes(locale);
  const fallbackLocale = asset.availableLocales[0];

  const openDownload = (versionId?: string) => {
    setRequestedVersionId(versionId ?? latestVersion?.id ?? null);
    setDownloadOpen(true);
    logEvent('asset.download_open', { assetId: asset.id, versionId: versionId ?? latestVersion?.id });
  };

  return (
    <>
      <Container size="2xl">
        <div className="pt-6 pb-20">
          <Breadcrumbs
            className="mb-6"
            items={[
              { label: tCommon('all'), href: '/' },
              { label: asset.category.name, href: `/search?categoryIds=${asset.category.id}` },
              { label: asset.title },
            ]}
          />

          <div className="grid lg:grid-cols-[1fr_360px] gap-8 lg:gap-12">
            <div className="min-w-0">
              <MediaGallery
                thumbnailUrl={asset.thumbnail.url}
                thumbnailFallback={asset.thumbnailAutoGenerated?.url}
                items={mediaItems}
                assetTitle={asset.title}
              />

              {!requestedLocaleAvailable && fallbackLocale ? (
                <Alert variant="info" className="mt-6">
                  {t('localeFallback', {
                    locale: t(`languageName.${fallbackLocale}` as 'languageName.en'),
                  })}
                </Alert>
              ) : null}

              {latestVersion ? (
                <div className="mt-8">
                  <AssetTabs
                    asset={asset}
                    activeVersion={latestVersion}
                    onDownloadVersion={openDownload}
                  />
                </div>
              ) : (
                <Alert variant="warning" className="mt-8">
                  {t('versions.noVersions')}
                </Alert>
              )}

              {meForComments ? (
                <CommentsSection asset={asset} me={meForComments} />
              ) : null}

              <RecommendedAssets assetId={asset.id} />
            </div>

            {/* Right rail */}
