'use client';

import { useMemo, useState } from 'react';
import NextLink from 'next/link';
import { Share2, Flag, Download } from 'lucide-react';
import { useLocale, useTranslations } from 'next-intl';
import { Container } from '@/components/layout/container';
import { Breadcrumbs } from '@/components/ui/breadcrumbs';
import { Button } from '@/components/ui/button';
import { Alert } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Avatar } from '@/components/ui/avatar';
import { avatarFromServer } from '@/lib/avatar';
import { AssetMeta } from './asset-meta';
import { VersionBadge } from './version-badge';
import { SaveButton } from './save-button';
import { MediaGallery, classifyFiles, type MediaItem } from './media-gallery';
import { AssetTabs } from './asset-tabs';
import { RecommendedAssets } from './recommended-assets';
import { DownloadPopup } from './download-popup';
import { ShareModal } from './share-modal';
import { ReportModal } from './report-modal';
import { CommentsSection } from '@/components/comments/comments-section';
import { formatDate, formatNumber } from '@/lib/format';
import { publicEnv } from '@/lib/env.public';
import { logEvent } from '@/lib/logger.events';
import { usePageView } from '@/lib/hooks/use-page-view';
import type { AssetDetail, AssetVersionPayload, LocaleCode, MeResponse } from '@/lib/api/types';

interface AssetDetailShellProps {
  asset: AssetDetail;
  currentUserId: string;
  isAdmin: boolean;
  me?: MeResponse;
}

export function AssetDetailShell({
  asset,
  currentUserId,
  isAdmin,
  me,
}: AssetDetailShellProps) {
  const meForComments = me;
  const t = useTranslations('asset');
  const tCommon = useTranslations('common');
  const locale = useLocale() as LocaleCode;
  const [downloadOpen, setDownloadOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [reportOpen, setReportOpen] = useState(false);
  const [requestedVersionId, setRequestedVersionId] = useState<string | null>(null);

  usePageView('asset.detail', { assetId: asset.id });

  const latestVersion = useMemo<AssetVersionPayload | null>(
    () => asset.versions.find((v) => v.isLatest) ?? asset.versions[0] ?? null,
    [asset.versions],
  );

  const isOwner = asset.owner.id === currentUserId;
  const showReport = !isOwner && !isAdmin;

  const mediaItems = useMemo<MediaItem[]>(() => {
    const items: MediaItem[] = [];
    const thumbUrl = asset.thumbnail.url ?? asset.thumbnailAutoGenerated?.url ?? null;
    if (thumbUrl) {
      items.push({
        id: `thumb-${asset.id}`,
        kind: 'image',
        url: thumbUrl,
        label: asset.title,
      });
    }
    // Owner-curated gallery from the publish wizard (image / video / audio / 3d).
    for (const m of asset.previewMedia ?? []) {
      if (m.visibility === 'hidden') continue; // never surfaced
      items.push({
        id: m.id,
        kind: m.kind,
        url: m.viewUrl,
        fullUrl: m.originalUrl ?? m.viewUrl,
        label: m.label,
        blur: m.visibility === 'blur',
        warning: m.warning,
      });
    }
    // Anything derivable from the asset's actual package files (e.g. a GLB
    // converted from an FBX, embedded textures with viewUrl metadata).
    if (latestVersion) items.push(...classifyFiles(latestVersion.files));
    return items;
  }, [asset, latestVersion]);

  const shareUrl =
    typeof window !== 'undefined'
      ? window.location.href
      : `${publicEnv.NEXT_PUBLIC_APP_URL.replace(/\/$/, '')}/assets/${asset.slug}`;

  const requestedLocaleAvailable = asset.availableLocales.includes(locale);
  const fallbackLocale = asset.availableLocales[0];

  const openDownload = (versionId?: string) => {
    setRequestedVersionId(versionId ?? latestVersion?.id ?? null);
    setDownloadOpen(true);
    logEvent('asset.download_open', { assetId: asset.id, versionId: versionId ?? latestVersion?.id });
  };

  return (
    <>
      <Container size="2xl">
        <div className="pt-6 pb-20">
          <Breadcrumbs
            className="mb-6"
            items={[
              { label: tCommon('all'), href: '/' },
              { label: asset.category.name, href: `/search?categoryIds=${asset.category.id}` },
              { label: asset.title },
            ]}
          />

          <div className="grid lg:grid-cols-[1fr_360px] gap-8 lg:gap-12">
            <div className="min-w-0">
              <MediaGallery
                thumbnailUrl={asset.thumbnail.url}
                thumbnailFallback={asset.thumbnailAutoGenerated?.url}
                items={mediaItems}
                assetTitle={asset.title}
              />

              {!requestedLocaleAvailable && fallbackLocale ? (
                <Alert variant="info" className="mt-6">
                  {t('localeFallback', {
                    locale: t(`languageName.${fallbackLocale}` as 'languageName.en'),
                  })}
                </Alert>
              ) : null}

              {latestVersion ? (
                <div className="mt-8">
                  <AssetTabs
                    asset={asset}
                    activeVersion={latestVersion}
                    onDownloadVersion={openDownload}
                  />
                </div>
              ) : (
                <Alert variant="warning" className="mt-8">
                  {t('versions.noVersions')}
                </Alert>
              )}

              {meForComments ? (
                <CommentsSection asset={asset} me={meForComments} />
              ) : null}

              <RecommendedAssets assetId={asset.id} />
            </div>

            {/* Right rail */}
            <aside className="lg:sticky lg:top-24 lg:self-start">
              <Card variant="outlined" padding="lg" className="!shadow-2">
                <h1 className="font-display text-h1 text-ink tracking-[-0.015em] leading-[1.15]">
                  {asset.title}
                </h1>
                <NextLink
                  href={`/?ownerId=${asset.owner.id}`}
                  className="mt-3 inline-flex items-center gap-2 text-body-sm text-ink-2 hover:text-ink transition-colors duration-120"
                >
                  <Avatar data={avatarFromServer(asset.owner.avatar)} size={24} />
                  <span>
                    {t('by')} <span className="font-medium text-ink">{asset.owner.displayName}</span>
                  </span>
                </NextLink>

                <div className="mt-5 flex items-center gap-2">
                  {!isOwner ? (
                    <SaveButton assetId={asset.id} initialSaved={asset.isSaved} variant="pill" />
                  ) : (
                    <Badge variant="warning">{t('youOwn')}</Badge>
                  )}
                  <button
                    type="button"
                    onClick={() => setShareOpen(true)}
                    aria-label={t('share')}
                    className="inline-flex h-10 w-10 items-center justify-center rounded-[12px] text-ink-2 hover:bg-surface-muted hover:text-ink transition-colors duration-120 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2"
                  >
                    <Share2 className="h-4 w-4" strokeWidth={2.25} />
                  </button>
                  {showReport ? (
                    <button
                      type="button"
                      onClick={() => setReportOpen(true)}
                      aria-label={t('report')}
                      className="inline-flex h-10 w-10 items-center justify-center rounded-[12px] text-ink-2 hover:bg-surface-muted hover:text-ink transition-colors duration-120 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2"
                    >
                      <Flag className="h-4 w-4" strokeWidth={2.25} />
                    </button>
                  ) : null}
                </div>

                <div className="mt-5">
                  <AssetMeta
                    engine={asset.engine}
                    categoryName={asset.category.name}
                    licenseName={asset.license.name}
                  />
                </div>

                {asset.tags.length > 0 ? (
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {asset.tags.map((tag) => (
                      <NextLink
                        key={tag.id}
                        href={`/search?tags=${tag.slug}`}
                        className="inline-flex items-center h-6 px-2.5 rounded-full bg-surface-muted text-[12px] font-medium text-ink-2 border border-line hover:border-ink/30 hover:text-ink transition-colors duration-120"
                      >
                        {tag.displayName}
                      </NextLink>
                    ))}
                  </div>
                ) : null}

                <dl className="mt-5 grid grid-cols-2 gap-3 text-caption">
                  <div>
                    <dt className="text-ink-3">{t('downloadsLifetime', { n: '' }).trim()}</dt>
                    <dd className="text-ink font-semibold text-[20px] geist-tnum">
                      {formatNumber(asset.totalDownloads, locale)}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-ink-3">{t('saves', { n: '' }).trim()}</dt>
                    <dd className="text-ink font-semibold text-[20px] geist-tnum">
                      {formatNumber(asset.totalSaves, locale)}
                    </dd>
                  </div>
                </dl>

                {latestVersion ? (
                  <>
                    <div className="mt-6 pt-5 border-t border-line">
                      <p className="text-caption text-ink-3 mb-2">{t('latestVersion')}</p>
                      <div className="flex items-center justify-between gap-2">
                        <VersionBadge semver={latestVersion.semver} isLatest size="md" />
                        <span className="text-caption text-ink-3 geist-tnum">
                          {latestVersion.publishedAt
                            ? formatDate(latestVersion.publishedAt, locale, { dateStyle: 'medium' })
                            : '—'}
                        </span>
                      </div>
                      <Button
                        size="lg"
                        fullWidth
                        className="mt-4"
                        onClick={() => openDownload()}
                        leadingIcon={<Download className="h-4 w-4" strokeWidth={2.25} />}
                      >
                        {t('download')}
                      </Button>
                      {asset.versions.length > 1 ? (
                        <button
                          type="button"
                          onClick={() => {
                            const tabs = document.getElementById('asset-tabs');
                            if (tabs) tabs.scrollIntoView({ behavior: 'smooth' });
                            window.location.hash = 'versions';
                          }}
                          className="mt-3 inline-flex items-center text-[13px] font-medium text-brand-blue hover:underline"
                        >
                          {t('viewOlderVersions')}
                        </button>
                      ) : null}
                    </div>
                  </>
                ) : null}

                <p className="mt-5 text-caption text-ink-3">
                  {t('availableIn', {
                    locales: asset.availableLocales
                      .map((l) => t(`languageName.${l}` as 'languageName.en'))
                      .join(', '),
                  })}
                </p>
              </Card>

              {/* Mobile-only sticky bottom CTA */}
              <div className="lg:hidden fixed bottom-0 left-0 right-0 z-30 bg-bg/95 backdrop-blur-[8px] border-t border-line p-3 flex items-center gap-2">
                {!isOwner ? (
                  <SaveButton assetId={asset.id} initialSaved={asset.isSaved} variant="ghost-pill" />
                ) : null}
                <Button
                  fullWidth
                  onClick={() => openDownload()}
                  leadingIcon={<Download className="h-4 w-4" strokeWidth={2.25} />}
                >
                  {t('download')}
                </Button>
              </div>
            </aside>
          </div>
        </div>
      </Container>

      {latestVersion ? (
        <DownloadPopup
          open={downloadOpen}
          onOpenChange={setDownloadOpen}
          assetId={asset.id}
          assetTitle={asset.title}
          initialVersionId={requestedVersionId ?? latestVersion.id}
        />
      ) : null}
      <ShareModal
        open={shareOpen}
        onOpenChange={setShareOpen}
        assetTitle={asset.title}
        url={shareUrl}
      />
      {showReport ? (
        <ReportModal
          open={reportOpen}
          onOpenChange={setReportOpen}
          assetId={asset.id}
          assetTitle={asset.title}
        />
      ) : null}
    </>
  );
}

