import { Injectable } from '@nestjs/common';
import { Asset, Locale, User } from '@prisma/client';
import { resolveAvatar } from '../../common/avatar/avatar';
import {
  LocalizedJson,
  pickTranslation,
  resolveLocalized,
} from '../../common/i18n/locale-resolver';
import { S3Service } from '../../infra/s3/s3.service';
import { AssetDetailDto, AssetSummaryDto, AssetVersionPayloadDto } from './dto/asset.dto';

type AssetWithRelations = Asset & {
  owner: User;
  category: { id: string; slug: string; name: unknown };
  license: { id: string; slug: string; name: string };
  translations: Array<{ locale: Locale; shortDescription: string; longDescription: unknown }>;
  tags: Array<{ tag: { id: string; slug: string; displayName: string } }>;
  versions: Array<{
    id: string;
    semver: string;
    releaseNotes: unknown;
    publishedAt: Date | null;
    isLatest: boolean;
    analysisStatus: string;
    bytesTotal: bigint;
    fileCount: number;
    files: Array<{ id: string; relativePath: string; kind: string; bytes: bigint; meta: unknown }>;
    compatibility: Array<{ engineVersion: string; renderPipelines: string[]; targets: string[] }>;
    dependencies: Array<{ name: string; version: string | null; source: string }>;
  }>;
  _count?: { libraryItems: number; downloads: number };
};

interface MapperContext {
  locale: Locale;
  /** When set, controls `isSaved/canEdit/canDelete/canArchive`. Null = guest. */
  requester: User | null;
  isSaved: boolean;
  totalDownloads: number;
  totalSaves: number;
}

/**
 * Folds the joined Prisma row into the public-facing detail / summary DTOs.
 * Centralized so any controller hydrating an Asset gets the same shape.
 */
@Injectable()
export class AssetMapperService {
  constructor(private readonly s3: S3Service) {}

  async toSummary(asset: AssetWithRelations, locale: Locale): Promise<AssetSummaryDto> {
    const translation = pickTranslation(asset.translations, locale);
    return {
      id: asset.id,
      slug: asset.slug,
      title: asset.title,
      shortDescription: translation?.shortDescription ?? '',
      engine: asset.engine,
      status: asset.status,
      thumbnailUrl: asset.thumbnailKey
        ? await this.s3.presignGet('thumbs', asset.thumbnailKey)
        : undefined,
      ownerDisplayName: asset.owner.displayName,
      categoryName:
        resolveLocalized(asset.category.name as LocalizedJson, locale) ?? asset.category.slug,
      totalDownloads: asset._count?.downloads ?? 0,
      totalSaves: asset._count?.libraryItems ?? 0,
      updatedAt: asset.updatedAt.toISOString(),
      publishedAt: asset.publishedAt?.toISOString(),
    };
  }

  /**
   * Batched summary mapper. Signs every asset's thumbnail in parallel rather
   * than awaiting per-asset, turning O(n × s3-roundtrip) into ~1 round-trip
   * for grid/list endpoints. Use this from Discover, Library, and admin
   * listings instead of `Promise.all(assets.map(toSummary))`.
   */
  async toSummaryMany(assets: AssetWithRelations[], locale: Locale): Promise<AssetSummaryDto[]> {
    const thumbUrls = await Promise.all(
      assets.map((a) =>
        a.thumbnailKey ? this.s3.presignGet('thumbs', a.thumbnailKey) : Promise.resolve(undefined),
      ),
    );
    return assets.map((asset, i) => {
      const translation = pickTranslation(asset.translations, locale);
      return {
        id: asset.id,
        slug: asset.slug,
        title: asset.title,
        shortDescription: translation?.shortDescription ?? '',
        engine: asset.engine,
        status: asset.status,
        thumbnailUrl: thumbUrls[i],
        ownerDisplayName: asset.owner.displayName,
        categoryName:
          resolveLocalized(asset.category.name as LocalizedJson, locale) ?? asset.category.slug,
        totalDownloads: asset._count?.downloads ?? 0,
        totalSaves: asset._count?.libraryItems ?? 0,
        updatedAt: asset.updatedAt.toISOString(),
        publishedAt: asset.publishedAt?.toISOString(),
      };
    });
  }

  async toDetail(asset: AssetWithRelations, ctx: MapperContext): Promise<AssetDetailDto> {
    const translation = pickTranslation(asset.translations, ctx.locale);
    const thumbnailUrl = asset.thumbnailKey
      ? await this.s3.presignGet('thumbs', asset.thumbnailKey)
      : undefined;
    // 3D auto-generated preview (Part 3 §3.5). Lives in the assets bucket
    // under the `__derived__/thumbnails/` prefix.
    const autoKey = (asset as Asset).thumbnailAutoGeneratedKey ?? undefined;
    const autoUrl = autoKey ? await this.s3.presignGet('assets', autoKey) : undefined;
    // Re-sign every preview-media item on read so the link the client sees is
    // always fresh (the bucket-side TTL is short). `viewUrl` points at the
    // compressed display variant when present (fast load); `originalUrl` is the
    // full-resolution object for click-to-enlarge.
    const previewMediaRaw = ((asset as Asset & { previewMedia?: unknown }).previewMedia ??
      []) as Array<{
      id?: unknown;
      kind?: unknown;
      key?: unknown;
      displayKey?: unknown;
      label?: unknown;
      mime?: unknown;
      visibility?: unknown;
      warning?: unknown;
    }>;
    const previewMedia = Array.isArray(previewMediaRaw)
      ? await Promise.all(
          previewMediaRaw
            .filter(
              (m) =>
                typeof m === 'object' && m && typeof m.key === 'string' && typeof m.id === 'string',
            )
            .map(async (m) => {
              const key = String(m.key);
              const displayKey = typeof m.displayKey === 'string' ? m.displayKey : undefined;
              const [originalUrl, displayUrl] = await Promise.all([
                this.s3.presignGet('editor', key),
                displayKey ? this.s3.presignGet('editor', displayKey) : Promise.resolve(undefined),
              ]);
              const visibility =
                m.visibility === 'blur' || m.visibility === 'hidden' ? m.visibility : 'visible';
              return {
                id: String(m.id),
                kind: (m.kind === 'video' || m.kind === 'audio' || m.kind === '3d'
                  ? m.kind
                  : 'image') as 'image' | 'video' | 'audio' | '3d',
                key,
                displayKey,
                label: typeof m.label === 'string' ? m.label : '',
                mime: typeof m.mime === 'string' ? m.mime : undefined,
                viewUrl: displayUrl ?? originalUrl,
                originalUrl,
                visibility: visibility as 'visible' | 'blur' | 'hidden',
                warning: typeof m.warning === 'string' ? m.warning : undefined,
              };
            }),
        )
      : [];

    const versions: AssetVersionPayloadDto[] = asset.versions
      .slice()
      .sort((a, b) => this.compareSemverDesc(a.semver, b.semver))
      .map((v) => ({
        id: v.id,
        semver: v.semver,
        releaseNotes: v.releaseNotes as object,
        publishedAt: v.publishedAt?.toISOString(),
        isLatest: v.isLatest,
        analysisStatus: v.analysisStatus,
        bytesTotal: v.bytesTotal.toString(),
        fileCount: v.fileCount,
        files: v.files.map((f) => ({
          id: f.id,
          relativePath: f.relativePath,
          kind: f.kind,
          bytes: f.bytes.toString(),
          meta: (f.meta as object | null) ?? undefined,
        })),
        compatibility: v.compatibility.map((c) => ({
          engineVersion: c.engineVersion,
          renderPipelines: c.renderPipelines,
          targets: c.targets,
        })),
        dependencies: v.dependencies.map((d) => ({
          name: d.name,
          version: d.version ?? undefined,
          source: d.source,
        })),
        requiresEmptyProject: asset.requiresEmptyProject,
      }));

    const canEdit =
      !!ctx.requester && (ctx.requester.id === asset.ownerId || ctx.requester.isAdmin);
    return {
      id: asset.id,
      slug: asset.slug,
      title: asset.title,
      shortDescription: translation?.shortDescription ?? '',
      longDescription: (translation?.longDescription as object) ?? null,
      availableLocales: asset.translations.map((t) => t.locale),
      engine: asset.engine,
      category: {
        id: asset.category.id,
        slug: asset.category.slug,
        name:
          resolveLocalized(asset.category.name as LocalizedJson, ctx.locale) ?? asset.category.slug,
      },
      license: { id: asset.license.id, slug: asset.license.slug, name: asset.license.name },
      tags: asset.tags.map((t) => ({
        id: t.tag.id,
        slug: t.tag.slug,
        displayName: t.tag.displayName,
      })),
      thumbnail: { key: asset.thumbnailKey ?? undefined, url: thumbnailUrl },
      thumbnailAutoGenerated: autoUrl ? { key: autoKey, url: autoUrl } : undefined,
      previewMedia,
      owner: {
        id: asset.owner.id,
        displayName: asset.owner.displayName,
        avatar: resolveAvatar(asset.owner.id, asset.owner.displayName, asset.owner.email),
      },
      versions,
      totalDownloads: ctx.totalDownloads,
      totalSaves: ctx.totalSaves,
      status: asset.status,
      publishedAt: asset.publishedAt?.toISOString(),
      updatedAt: asset.updatedAt.toISOString(),
      createdAt: asset.createdAt.toISOString(),
      isSaved: ctx.isSaved,
      canEdit,
      canDelete: canEdit,
      canArchive: canEdit && asset.status === 'PUBLISHED',
    };
  }

  /** Numeric semver comparator (descending). Assumes `^\d+\.\d+\.\d+$`. */
  private compareSemverDesc(a: string, b: string): number {
    const [ax, ay, az] = a.split('.').map(Number);
    const [bx, by, bz] = b.split('.').map(Number);
    return bx - ax || by - ay || bz - az;
  }
}
