'use client';

import { useTranslations, useLocale } from 'next-intl';
import { Pencil, FileCheck2 } from 'lucide-react';
import { useWizard, type WizardStep } from '../wizard-context';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { EngineLogo, engineLabels } from '@/components/asset/engine-logo';
import { VersionBadge } from '@/components/asset/version-badge';
import { Alert } from '@/components/ui/alert';
import { formatBytes } from '@/lib/format';
import type { LocaleCode } from '@/lib/api/types';

export function StepReview() {
  const wiz = useWizard();
  const t = useTranslations('publish.review');
  const tBasics = useTranslations('publish.basics');
  const tMedia = useTranslations('publish.media');
  const tFiles = useTranslations('publish.files');
  const tCompat = useTranslations('publish.compatibility');
  const tLicense = useTranslations('publish.licenseStep');
  const locale = useLocale() as LocaleCode;

  const v = wiz.latestVersion;
  const thumb = wiz.asset.thumbnail.url ?? wiz.asset.thumbnailAutoGenerated?.url ?? null;
  const goto = (step: WizardStep) => wiz.setStep(step);

  return (
    <div className="space-y-6 max-w-[820px]">
      <div>
        <h2 className="font-display text-h2 text-ink tracking-[-0.01em] mb-1">{t('title')}</h2>
        <p className="text-body-sm text-ink-3">{t('subtitle')}</p>
      </div>

      <Card>
        <SectionHead title={tBasics('title')} onEdit={() => goto('basics')} />
        <dl className="grid sm:grid-cols-2 gap-x-6 gap-y-2 text-[14px]">
          <Row label="Title" value={wiz.asset.title || '—'} />
          <Row label={tBasics('slug')} value={wiz.asset.slug || '—'} mono />
          <Row
            label={tBasics('engine')}
            value={
              <span className="inline-flex items-center gap-2">
                <EngineLogo engine={wiz.asset.engine} size="sm" />
                {engineLabels[wiz.asset.engine]}
              </span>
            }
          />
          <Row label={tBasics('category')} value={wiz.asset.category?.name ?? '—'} />
          <Row label={tBasics('license')} value={wiz.asset.license?.name ?? '—'} />
          <Row label={tBasics('semver')} value={v ? <VersionBadge semver={v.semver} isLatest size="sm" /> : '—'} />
        </dl>
      </Card>

      <Card>
        <SectionHead title={tMedia('thumbnailTitle')} onEdit={() => goto('media')} />
        {thumb ? (
          <div className="rounded-[14px] overflow-hidden border border-line max-w-[420px]">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={thumb} alt="" className="block w-full aspect-[16/9] object-cover" />
          </div>
        ) : (
          <Alert variant="warning">No thumbnail yet.</Alert>
        )}
      </Card>

      <Card>
        <SectionHead title={tFiles('title')} onEdit={() => goto('files')} />
        {v && v.fileCount > 0 ? (
          <p className="text-body-sm text-ink-2 geist-tnum">
            {v.fileCount} files · {formatBytes(v.bytesTotal, locale)}
          </p>
        ) : (
          <Alert variant="warning">No files uploaded.</Alert>
        )}
        {v?.dependencies?.length ? (
          <div className="mt-3">
            <p className="text-eyebrow uppercase tracking-[0.12em] text-ink-3 mb-2">
              Dependencies
            </p>
            <ul className="text-caption text-ink-2 grid sm:grid-cols-2 gap-x-4 gap-y-0.5 font-mono">
              {v.dependencies.map((d, i) => (
                <li key={i}>
                  {d.name}
                  {d.version ? `@${d.version}` : ''}
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </Card>

      <Card>
        <SectionHead title="Description" onEdit={() => goto('description')} />
        <p className="text-body-sm text-ink-2">{wiz.asset.shortDescription || '—'}</p>
        <p className="mt-2 text-caption text-ink-3">
          Available locales: {wiz.asset.availableLocales.join(', ') || '—'}
        </p>
      </Card>

      {wiz.asset.engine !== 'ENGINE_AGNOSTIC' ? (
