import { Asset, AssetEngine, AssetStatus } from '@prisma/client';
import { PublishChecklistService } from '../../src/modules/assets/publish-checklist.service';

function makeAsset(overrides: Partial<Asset> = {}): Asset {
  return {
    id: 'cln_asset',
    slug: 'demo-asset',
    title: 'Demo',
    ownerId: 'cln_user',
    categoryId: 'cat_id',
    licenseId: 'lic_id',
    engine: AssetEngine.UNITY,
    status: AssetStatus.DRAFT,
    thumbnailKey: 'thumbs/cln_asset/thumb.png',
    thumbnailVariants: null,
    thumbnailAutoGeneratedKey: null,
    previewMedia: null,
    requiresEmptyProject: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: null,
    archivedAt: null,
    ...overrides,
  };
}

describe('PublishChecklistService', () => {
  it('flags every missing prerequisite at once', async () => {
    const prisma = {
      assetTranslation: { count: jest.fn().mockResolvedValue(0) },
      assetVersion: { findFirst: jest.fn().mockResolvedValue(null) },
    } as never;
    const svc = new PublishChecklistService(prisma);
    const asset = makeAsset({ thumbnailKey: null, categoryId: '', licenseId: '' });
    const violations = await svc.evaluate(asset);
    const codes = violations.map((v) => v.code).sort();
    expect(codes).toEqual(
