name: CD - Image Worker

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Compute image tag
        id: meta
        run: |
          echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          echo "ts=$(date -u +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.worker
          push: true
          platforms: linux/amd64
          tags: |
            ${{ vars.DOCKERHUB_USERNAME}}/${{ vars.IMAGE_NAME }}:${{ inputs.tag }}
            ${{ vars.DOCKERHUB_USERNAME}}/${{ vars.IMAGE_NAME }}:${{ inputs.tag }}-${{ steps.meta.outputs.ts }}
            ${{ vars.DOCKERHUB_USERNAME}}/${{ vars.IMAGE_NAME }}:${{ inputs.tag }}-${{ steps.meta.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
