name: CD - Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build-image-worker:
    name: Build & Push Worker Image
    uses: ./.github/workflows/image-worker.yml
    needs: ci
    with:
      tag: worker-latest
    secrets: inherit

  build-image-api:
    name: Build & Push API Image
    uses: ./.github/workflows/image-api.yml
    needs: ci
    with:
      tag: api-latest
    secrets: inherit
