import { Injectable } from '@nestjs/common';
import { PutObjectCommand } from '@aws-sdk/client-s3';
import { Job } from 'bullmq';
import { readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import sharp from 'sharp';
import { AppConfigService } from '../../../../config/app-config.service';
import { PrismaService } from '../../../../infra/prisma/prisma.service';
import { S3Service } from '../../../../infra/s3/s3.service';
import { SentryService } from '../../../../infra/sentry/sentry.service';
import { ThumbnailRenderJob } from '../../contracts';
import { QUEUE } from '../../queue-names';
import { JobWorkerBase } from '../../worker-base';
import { openScratch } from '../analyze/scratch';
import { runSubprocess } from '../analyze/subprocess';

/**
 * Renders a neutral-lit preview from the version's converted GLB. We pick
 * the file with the most vertices when more than one GLB exists — heuristic
 * for "most representative" mesh. The resulting WebP becomes the asset's
 * secondary preview (`thumbnailAutoGeneratedKey`).
 */
@Injectable()
export class ThumbnailRenderWorker extends JobWorkerBase<ThumbnailRenderJob> {
  constructor(
    config: AppConfigService,
    sentry: SentryService,
    private readonly s3: S3Service,
    private readonly prisma: PrismaService,
  ) {
    super(QUEUE.THUMBNAIL_RENDER, config, sentry);
  }

  async process(job: Job<ThumbnailRenderJob>): Promise<void> {
    const { versionId, glbKey } = job.data;
    const version = await this.prisma.assetVersion.findUnique({
      where: { id: versionId },
      include: { asset: true, files: true },
    });
    if (!version) return;

    // Only the largest GLB in the version becomes the preview. Other GLBs
    // for the same version are skipped — we still want a single canonical
    // auto-thumbnail per asset.
    const largest = this.pickLargestGlb(version.files);
    if (largest && largest !== glbKey) {
      this.logger.debug(`Skipping render for ${glbKey} — ${largest} is the larger candidate.`);
      return;
    }

    const timeoutMs = this.config.get('GLTF_CONVERT_TIMEOUT_SEC') * 1000;
    const scratch = await openScratch(
      this.s3,
      'assets',
      glbKey,
      job.id ?? `job-${Date.now()}`,
      this.config.get('WORKER_SCRATCH_DIR'),
    );
    const pngPath = join(scratch.dir, 'render.png');
    const renderScript = join(process.cwd(), 'scripts', 'blender', 'render_glb_preview.py');
    try {
      const res = await runSubprocess(
        this.config.get('BLENDER_BIN'),
        ['-b', '-P', renderScript, '--', scratch.filePath, pngPath, this.config.get('HDRI_PATH')],
        { timeoutMs },
      );
      if (res.exitCode !== 0) {
        throw new Error(`Blender render exit ${res.exitCode}: ${res.stderr.slice(-512)}`);
      }
      const png = await readFile(pngPath);
      const webp1x = await sharp(png)
        .resize(1280, 720, { fit: 'cover' })
        .webp({ quality: 86 })
        .toBuffer();
      const webp2x = await sharp(png)
        .resize(2560, 1440, { fit: 'cover' })
        .webp({ quality: 86 })
        .toBuffer();
      const baseKey = `${version.s3Prefix}__derived__/thumbnails/auto`;
      await this.s3.client.send(
        new PutObjectCommand({
          Bucket: this.s3.bucketFor('assets'),
          Key: `${baseKey}.webp`,
          Body: webp1x,
          ContentType: 'image/webp',
        }),
      );
      await this.s3.client.send(
        new PutObjectCommand({
          Bucket: this.s3.bucketFor('assets'),
          Key: `${baseKey}-2x.webp`,
          Body: webp2x,
          ContentType: 'image/webp',
        }),
      );
      await this.prisma.asset.update({
        where: { id: version.assetId },
        data: { thumbnailAutoGeneratedKey: `${baseKey}.webp` },
      });
    } finally {
      await scratch.cleanup();
      await rm(pngPath, { force: true });
    }
  }

  /** Returns the S3 key of the largest derived GLB across the version. */
  private pickLargestGlb(
    files: Array<{ s3Key: string; meta: unknown; bytes: bigint }>,
  ): string | null {
    let bestKey: string | null = null;
    let bestVerts = -1;
    let bestBytes = -1n;
    for (const f of files) {
      const meta = (f.meta as Record<string, unknown> | null) ?? {};
      const webViewerGlb = meta.webViewerGlb as { key?: string; bytes?: number } | undefined;
      if (!webViewerGlb?.key) continue;
      const vertices = Number((meta as { vertices?: number }).vertices ?? 0);
      const candidateBytes = BigInt(webViewerGlb.bytes ?? 0);
      if (vertices > bestVerts || (vertices === bestVerts && candidateBytes > bestBytes)) {
        bestVerts = vertices;
        bestBytes = candidateBytes;
        bestKey = webViewerGlb.key;
      }
    }
    return bestKey;
  }
}
