import { Injectable } from '@nestjs/common';
import { PutObjectCommand } from '@aws-sdk/client-s3';
import { Job } from 'bullmq';
import { readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import sharp from 'sharp';
import { AppConfigService } from '../../../../config/app-config.service';
import { PrismaService } from '../../../../infra/prisma/prisma.service';
import { S3Service } from '../../../../infra/s3/s3.service';
import { SentryService } from '../../../../infra/sentry/sentry.service';
import { ThumbnailRenderJob } from '../../contracts';
import { QUEUE } from '../../queue-names';
import { JobWorkerBase } from '../../worker-base';
import { openScratch } from '../analyze/scratch';
import { runSubprocess } from '../analyze/subprocess';

/**
 * Renders a neutral-lit preview from the version's converted GLB. We pick
 * the file with the most vertices when more than one GLB exists — heuristic
 * for "most representative" mesh. The resulting WebP becomes the asset's
 * secondary preview (`thumbnailAutoGeneratedKey`).
 */
@Injectable()
export class ThumbnailRenderWorker extends JobWorkerBase<ThumbnailRenderJob> {
  constructor(
    config: AppConfigService,
    sentry: SentryService,
    private readonly s3: S3Service,
    private readonly prisma: PrismaService,
  ) {
    super(QUEUE.THUMBNAIL_RENDER, config, sentry);
  }

  async process(job: Job<ThumbnailRenderJob>): Promise<void> {
    const { versionId, glbKey } = job.data;
    const version = await this.prisma.assetVersion.findUnique({
      where: { id: versionId },
      include: { asset: true, files: true },
    });
    if (!version) return;

    // Only the largest GLB in the version becomes the preview. Other GLBs
    // for the same version are skipped — we still want a single canonical
    // auto-thumbnail per asset.
    const largest = this.pickLargestGlb(version.files);
    if (largest && largest !== glbKey) {
      this.logger.debug(`Skipping render for ${glbKey} — ${largest} is the larger candidate.`);
      return;
    }

    const timeoutMs = this.config.get('GLTF_CONVERT_TIMEOUT_SEC') * 1000;
    const scratch = await openScratch(
      this.s3,
      'assets',
      glbKey,
      job.id ?? `job-${Date.now()}`,
      this.config.get('WORKER_SCRATCH_DIR'),
    );
    const pngPath = join(scratch.dir, 'render.png');
    const renderScript = join(process.cwd(), 'scripts', 'blender', 'render_glb_preview.py');
    try {
      const res = await runSubprocess(
        this.config.get('BLENDER_BIN'),
        ['-b', '-P', renderScript, '--', scratch.filePath, pngPath, this.config.get('HDRI_PATH')],
        { timeoutMs },
      );
      if (res.exitCode !== 0) {
        throw new Error(`Blender render exit ${res.exitCode}: ${res.stderr.slice(-512)}`);
